/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ac.id.stikompoltek;

import ac.id.stikompoltek.dto.Kereta;
import ac.id.stikompoltek.service.KeretaService;
import ac.id.stikompoltek.utils.Database;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author aji
 */
public class KeretaFrame extends javax.swing.JInternalFrame {
    
    private Database database;

    /**
     * Creates new form KeretaFrame
     */
    public KeretaFrame() {
        initComponents();
        resetView();
    }
    
    // Reset View
    public void resetView() {
        fillTableData();
        this.lblIdKereta.setText("0");
        this.txtNamaKereta.setText("");
        this.setTitle("Kereta | MODE : INSERT");
    }
    
    // Fill table data
    private void fillTableData() {
        this.tblKereta.setModel(new TableKeretaModel());
    }
    
    public class TableKeretaModel extends AbstractTableModel {
        
        private List<Kereta> keretas;
        private String[] columnName = {"Id Kota", "Nama Kereta"};
        
        TableKeretaModel() {
            database = new KeretaService();
            this.keretas = database.getAll();
        }

        @Override
        public int getRowCount() {
            return this.keretas.size();
        }

        @Override
        public int getColumnCount() {
            return this.columnName.length;
        }
        
        @Override
        public String getColumnName(int index) {
            return this.columnName[index];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Kereta kereta = this.keretas.get(rowIndex);
            switch(columnIndex) {
                case 0:
                    return kereta.getIdKereta();
                case 1:
                    return kereta.getNamaKereta();
                default:
                    return "";
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamaKereta = new javax.swing.JTextField();
        btnSaveKereta = new javax.swing.JButton();
        btnResetKereta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKereta = new javax.swing.JTable();
        lblIdKeretasss = new javax.swing.JLabel();
        lblIdKereta = new javax.swing.JLabel();
        btnDeleteKereta = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Kereta");
        setToolTipText("");

        jLabel1.setText("Nama Kereta");

        btnSaveKereta.setText("Simpan");
        btnSaveKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveKeretaActionPerformed(evt);
            }
        });

        btnResetKereta.setText("Reset");
        btnResetKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetKeretaActionPerformed(evt);
            }
        });

        tblKereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKeretaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKereta);

        lblIdKeretasss.setText("Id");

        lblIdKereta.setText("0");

        btnDeleteKereta.setText("Delete");
        btnDeleteKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKeretaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaKereta, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(lblIdKereta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdKeretasss)
                    .addComponent(btnSaveKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdKeretasss)
                    .addComponent(lblIdKereta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSaveKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnResetKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveKeretaActionPerformed
        this.database = new KeretaService();
        Kereta kereta = new Kereta();
        kereta.setIdKereta(Integer.parseInt(this.lblIdKereta.getText()));
        kereta.setNamaKereta(this.txtNamaKereta.getText());
        this.database.save(kereta);
        resetView();
    }//GEN-LAST:event_btnSaveKeretaActionPerformed

    private void btnResetKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKeretaActionPerformed
        resetView();
    }//GEN-LAST:event_btnResetKeretaActionPerformed

    private void tblKeretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeretaMouseClicked
        this.database = new KeretaService();
        Kereta kereta = (Kereta)this.database.getById((int)this.tblKereta.getValueAt(this.tblKereta.getSelectedRow(), 0));
        this.lblIdKereta.setText(String.valueOf(kereta.getIdKereta()));
        this.txtNamaKereta.setText(kereta.getNamaKereta());
        this.setTitle("Kereta | MODE : EDIT / DELETE");
    }//GEN-LAST:event_tblKeretaMouseClicked

    private void btnDeleteKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKeretaActionPerformed
        if(!this.lblIdKereta.getText().equals("")) {
            this.database = new KeretaService();
            Kereta kereta = (Kereta) this.database.getById(Integer.parseInt(this.lblIdKereta.getText()));
            this.database.delete(kereta);
            resetView();
        }
    }//GEN-LAST:event_btnDeleteKeretaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteKereta;
    private javax.swing.JButton btnResetKereta;
    private javax.swing.JButton btnSaveKereta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdKereta;
    private javax.swing.JLabel lblIdKeretasss;
    private javax.swing.JTable tblKereta;
    private javax.swing.JTextField txtNamaKereta;
    // End of variables declaration//GEN-END:variables
}
